// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// trstatWrapper
DataFrame trstatWrapper(int ncol, IntegerVector table, IntegerVector uwt, int sampsz, int rowm, int m_trt_switch, int obsstat, int obscorr_0, int obscorr_1, double pval);
RcppExport SEXP _rema_trstatWrapper(SEXP ncolSEXP, SEXP tableSEXP, SEXP uwtSEXP, SEXP sampszSEXP, SEXP rowmSEXP, SEXP m_trt_switchSEXP, SEXP obsstatSEXP, SEXP obscorr_0SEXP, SEXP obscorr_1SEXP, SEXP pvalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type table(tableSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type uwt(uwtSEXP);
    Rcpp::traits::input_parameter< int >::type sampsz(sampszSEXP);
    Rcpp::traits::input_parameter< int >::type rowm(rowmSEXP);
    Rcpp::traits::input_parameter< int >::type m_trt_switch(m_trt_switchSEXP);
    Rcpp::traits::input_parameter< int >::type obsstat(obsstatSEXP);
    Rcpp::traits::input_parameter< int >::type obscorr_0(obscorr_0SEXP);
    Rcpp::traits::input_parameter< int >::type obscorr_1(obscorr_1SEXP);
    Rcpp::traits::input_parameter< double >::type pval(pvalSEXP);
    rcpp_result_gen = Rcpp::wrap(trstatWrapper(ncol, table, uwt, sampsz, rowm, m_trt_switch, obsstat, obscorr_0, obscorr_1, pval));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rema_trstatWrapper", (DL_FUNC) &_rema_trstatWrapper, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_rema(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
