# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

trstatWrapper <- function(ncol, table, uwt, sampsz, rowm, m_trt_switch, obsstat, obscorr_0, obscorr_1, pval) {
    .Call(`_rema_trstatWrapper`, ncol, table, uwt, sampsz, rowm, m_trt_switch, obsstat, obscorr_0, obscorr_1, pval)
}

